name: Code quality

on:
    # Enable manual run
    workflow_dispatch:
    # Run on every push; this also covers pull requests
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"
                  cache: true
            - run: sudo apt-get update && sudo apt-get install libsodium-dev
            - run:
                  "./scripts/lint.sh"
                  # - run: "go test ./..."
