name: Prod CI

on:
    workflow_dispatch:
    # Enable manual run
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v*" # Push events to matching v*, i.e. v4.2.0

jobs:
    build:
        # This job will run on ubuntu virtual machine
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Check out code

            - uses: mr-smithers-excellent/docker-build-push@v6
              name: Build & Push
              with:
                  image: ente/museum-prod
                  registry: rg.fr-par.scw.cloud
                  enableBuildKit: true
                  buildArgs: GIT_COMMIT=${GITHUB_SHA}
                  tags: ${GITHUB_SHA}, latest
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
