name = "health-check"
main = "src/index.ts"
compatibility_date = "2024-06-14"

[vars]
# Added as a secret via the Cloudflare dashboard
# NOTIFY_URL = ""
# CHAT_ID = ""

# Disable the default route, this worker does not handle fetch.
workers_dev = false

[triggers]
# Every minute
crons = [ "*/1 * * * *" ]

tail_consumers = [{ service = "tail" }]
