name: "Release (cli)"

on:
    push:
        # Run when a tag matching the pattern "cli-v*"" is pushed
        #
        # Tip: to test this workflow, push at tag with a pre-release version,
        # e.g. `cli-v1.2.3-test`, where 1.2.3 is the expected version number of
        # the next release that'll go out.
        tags:
            - "cli-v*"

jobs:
    release-linux-amd64:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: wangyoucao577/go-release-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  goversion: "1.20"
                  project_path: "./cli"
                  sha256sum: true
                  goos: linux
                  goarch: amd64
