name: "Release (cli)"

on:
    push:
        # Run when a tag matching the pattern "cli-v*"" is pushed
        #
        # Tip: to test this workflow, push at tag with a pre-release version,
        # e.g. `cli-v1.2.3-test`, where 1.2.3 is the expected version number of
        # the next release that'll go out.
        tags:
            - "cli-v*"

jobs:
    release-linux-amd64:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create a draft GitHub release
              uses: ncipollo/release-action@v1
              with:
                  prerelease: true
                  draft: true
                  allowUpdates: true
                  updateOnlyUnreleased: true

            - name: Build go binaries and upload to the release
              uses: wangyoucao577/go-release-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  release_tag: ${{ github.ref_name }}
                  release_name: ${{ github.ref_name }}
                  goversion: "1.20"
                  project_path: "./cli"
                  sha256sum: true
                  goos: linux
                  goarch: amd64
