name: "Lint (mobile)"

on:
    # Run on every push (this also covers pull requests)
    push:
        # See: [Note: Specify branch when specifying a path filter]
        branches: ["**"]
        # Only run if something changes in these paths
        paths:
            - "mobile/**"
            - ".github/workflows/mobile-lint.yml"

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: mobile
        steps:
            # Checkout our code, including submodules
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            # Install Flutter
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: "3.13.4"
                  cache: true

            # Install dependencies
            - run: flutter pub get

            # Lint
            - run: flutter analyze --no-fatal-infos
