name: "Lint (web)"

on:
    # Run on every push (this also covers pull requests)
    push:
        paths:
            # - But only if something changes inside web
            - "web/**"
            # - Or if the there is some change in GitHub workflows themselves
            - ".github/workflows/**"

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: web
        steps:
            - uses: actions/checkout@v4
            - run: yarn install
            - run: yarn lint
