name: "Lint (web)"

on:
    # Run on every push to a branch other than main that changes web/
    push:
        branches-ignore: [main]
        paths:
            - "web/**"
            - ".github/workflows/web-lint.yml"

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: web
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node and enable yarn caching
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"
                  cache-dependency-path: "web/yarn.lock"

            - name: Install dependencies
              run: yarn install && yarn run next telemetry disable

            - run: yarn lint
